language: en

pipeline:
- name: ConveRTTokenizer
- name: ConveRTFeaturizer
  model_url: https://github.com/davidalami/ConveRT/releases/download/1.0/nocontext_tf_model.tar.gz
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: DIETClassifier
  epochs: 9
  scale_loss: False
  weight_sparsity: 0.3
  transformer_size: 512
  BILOU_flag: True
- name: ResponseSelector
  epochs: 10
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 3
  batch_strategy: balanced
  epochs: 10
  random_seed: 666
  evaluate_on_num_examples: 0
- name: RulePolicy
