language: en
pipeline:
- name: ConveRTTokenizer  
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: ConveRTFeaturizer
- name: DIETClassifier
  hidden_layers_sizes:
    text: [256, 128]
    label: []
  intent_classification: True
  entity_recognition: True
  use_masked_language_model: False
  BILOU_flag: False
  number_of_transformer_layers: 2
  epochs: 50
- name: ResponseSelector
  epochs: 200
policies:
- name: MemoizationPolicy
- name: EmbeddingPolicy
  max_history: 5
  batch_strategy: balanced
  epochs: 50
  random_seed: 666
  evaluate_on_num_examples: 0
- name: MappingPolicy
- name: FormPolicy
